import { Request, Response } from 'express';

export const findMatches = (req: Request, res: Response) => {
  console.log('req.body', req.body);
  console.log('Match request received:', req.body);

  // Extensive mock data with 100+ diverse coach profiles
  const matches = [
    // Excellent Matches (90%+)
    {
      id: "1",
      name: "Richard Peng",
      specialties: ["Anxiety", "Depression"],
      modalities: ["ACT", "Mindfulness-Based Coaching", "Values-Based Action Planning"],
      location: ["CA", "NY"],
      demographics: { gender: "Male", ethnicity: "Asian American, Taiwanese", religion: "None" },
      availability: 2,
      matchScore: 95,
      languages: ["English"],
      bio: "I'm a certified ACT coach specializing in anxiety and stress management. Using acceptance and commitment therapy principles, I've spent over 10 years helping clients develop psychological flexibility, align with their values, and build resilience in their daily lives.",
      sexualOrientation: "Gay / lesbian",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "2",
      name: "Alice Zhang",
      specialties: ["Depression", "Mindfulness"],
      modalities: ["ACT", "Mindfulness-Based Stress Reduction", "Values Clarification", "Committed Action Planning"],
      location: ["CA"],
      demographics: { gender: "Female", ethnicity: "Chinese Canadian", religion: "Buddhist" },
      availability: 10,
      matchScore: 94,
      languages: ["English", "Hindi", "French"],
      bio: "I'm a certified ACT coach with expertise in mindfulness and values-based living. I focus on supporting clients experiencing low mood and stress by integrating ACT principles, mindfulness practices, and helping them connect with what matters most to find meaning and vitality in their lives.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "3",
      name: "Maria Rodriguez",
      specialties: ["Trauma Recovery", "Anxiety", "Depression"],
      modalities: ["ACT", "EMDR", "Trauma-Informed Care"],
      location: ["TX", "FL"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 5,
      matchScore: 93,
      languages: ["English", "Spanish"],
      bio: "Bilingual ACT coach specializing in trauma recovery and anxiety management. I help clients heal from past experiences while building psychological flexibility and reconnecting with their core values.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekday Evenings"]
    },
    {
      id: "4",
      name: "David Thompson",
      specialties: ["Work Stress", "Relationships", "Life Transitions"],
      modalities: ["ACT", "Values-Based Living", "Mindfulness"],
      location: ["NY", "NJ"],
      demographics: { gender: "Male", ethnicity: "White", religion: "Christian" },
      availability: 8,
      matchScore: 92,
      languages: ["English"],
      bio: "Executive coach with 15 years of experience helping professionals navigate workplace stress and major life transitions using ACT principles.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "5",
      name: "Keisha Williams",
      specialties: ["Racial Identity", "Academic Stress", "Self-Esteem"],
      modalities: ["ACT", "Cultural Awareness", "Identity Development"],
      location: ["GA", "SC"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "Baptist" },
      availability: 6,
      matchScore: 91,
      languages: ["English"],
      bio: "Specializing in racial identity exploration and academic success using ACT frameworks. I help students and professionals embrace their authentic selves while achieving their goals.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "6",
      name: "Dr. Sarah Kim",
      specialties: ["Anxiety", "Perfectionism", "Work-Life Balance"],
      modalities: ["ACT", "Mindfulness", "Self-Compassion"],
      location: ["WA", "OR"],
      demographics: { gender: "Female", ethnicity: "Korean American", religion: "None" },
      availability: 4,
      matchScore: 90,
      languages: ["English", "Korean"],
      bio: "Former therapist turned ACT coach, specializing in helping high-achievers overcome perfectionism and find work-life balance through mindfulness and values alignment.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },

    // Good Matches (75-89%)
    {
      id: "7",
      name: "James Mitchell",
      specialties: ["Depression", "Grief", "Addiction Recovery"],
      modalities: ["ACT", "Grief Counseling", "Recovery Support"],
      location: ["CO", "UT"],
      demographics: { gender: "Male", ethnicity: "White", religion: "None" },
      availability: 7,
      matchScore: 89,
      languages: ["English"],
      bio: "ACT coach with personal experience in addiction recovery. I help clients process grief and depression while building commitment to meaningful life changes.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "8",
      name: "Priya Patel",
      specialties: ["Anxiety", "Cultural Identity", "Family Relationships"],
      modalities: ["ACT", "Family Systems", "Cultural Integration"],
      location: ["CA", "NV"],
      demographics: { gender: "Female", ethnicity: "Indian American", religion: "Hindu" },
      availability: 9,
      matchScore: 88,
      languages: ["English", "Hindi", "Gujarati"],
      bio: "First-generation immigrant coach helping clients navigate cultural identity and family expectations while staying true to personal values through ACT principles.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "9",
      name: "Michael Chen",
      specialties: ["Work Stress", "Leadership", "Performance Anxiety"],
      modalities: ["ACT", "Executive Coaching", "Performance Psychology"],
      location: ["NY", "CT"],
      demographics: { gender: "Male", ethnicity: "Chinese American", religion: "None" },
      availability: 3,
      matchScore: 87,
      languages: ["English", "Mandarin"],
      bio: "Executive ACT coach specializing in leadership development and performance optimization for professionals in high-pressure environments.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "10",
      name: "Jessica Brown",
      specialties: ["Eating Disorders", "Body Image", "Self-Acceptance"],
      modalities: ["ACT", "Body Positive Coaching", "Intuitive Eating"],
      location: ["IL", "WI"],
      demographics: { gender: "Female", ethnicity: "White", religion: "None" },
      availability: 8,
      matchScore: 86,
      languages: ["English"],
      bio: "Body-positive ACT coach helping clients develop healthy relationships with food and body image through acceptance and values-based living.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "11",
      name: "Carlos Martinez",
      specialties: ["Trauma", "PTSD", "Veterans Support"],
      modalities: ["ACT", "Trauma-Informed Care", "EMDR"],
      location: ["TX", "NM"],
      demographics: { gender: "Male", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 5,
      matchScore: 85,
      languages: ["English", "Spanish"],
      bio: "Military veteran and ACT coach specializing in trauma recovery and PTSD support for veterans and first responders.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "12",
      name: "Amanda Johnson",
      specialties: ["Chronic Pain", "Health Anxiety", "Medical Trauma"],
      modalities: ["ACT", "Pain Psychology", "Medical Mindfulness"],
      location: ["FL", "AL"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Christian" },
      availability: 6,
      matchScore: 84,
      languages: ["English"],
      bio: "Health psychology ACT coach helping clients manage chronic conditions while maintaining quality of life and psychological well-being.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekday Evenings"]
    },
    {
      id: "13",
      name: "Robert Lee",
      specialties: ["Anger Management", "Relationship Issues", "Communication"],
      modalities: ["ACT", "Emotional Regulation", "Communication Skills"],
      location: ["NC", "VA"],
      demographics: { gender: "Male", ethnicity: "Korean American", religion: "None" },
      availability: 7,
      matchScore: 83,
      languages: ["English"],
      bio: "ACT coach specializing in emotional regulation and relationship dynamics, helping clients develop healthier communication patterns and manage anger constructively.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "14",
      name: "Dr. Rachel Green",
      specialties: ["Academic Stress", "Career Transitions", "Imposter Syndrome"],
      modalities: ["ACT", "Career Coaching", "Academic Support"],
      location: ["MA", "NH"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Jewish" },
      availability: 4,
      matchScore: 82,
      languages: ["English"],
      bio: "Former academic turned ACT coach, specializing in helping graduate students and professionals overcome imposter syndrome and navigate career transitions.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "15",
      name: "Jamal Washington",
      specialties: ["Racial Trauma", "Social Justice", "Community Advocacy"],
      modalities: ["ACT", "Social Justice Coaching", "Community Healing"],
      location: ["DC", "MD"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "None" },
      availability: 8,
      matchScore: 81,
      languages: ["English"],
      bio: "Community organizer and ACT coach focusing on racial healing and social justice advocacy while maintaining personal well-being and psychological flexibility.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "16",
      name: "Lisa Wong",
      specialties: ["Parenting", "Family Dynamics", "Work-Life Balance"],
      modalities: ["ACT", "Parenting Support", "Family Coaching"],
      location: ["CA", "AZ"],
      demographics: { gender: "Female", ethnicity: "Chinese American", religion: "None" },
      availability: 9,
      matchScore: 80,
      languages: ["English", "Mandarin"],
      bio: "Working mother and ACT coach helping parents balance career demands with family life while staying connected to their values and maintaining well-being.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "17",
      name: "Thomas Anderson",
      specialties: ["Addiction Recovery", "Relapse Prevention", "Life Skills"],
      modalities: ["ACT", "Recovery Coaching", "Behavioral Change"],
      location: ["OH", "IN"],
      demographics: { gender: "Male", ethnicity: "White", religion: "Christian" },
      availability: 6,
      matchScore: 79,
      languages: ["English"],
      bio: "Recovery specialist using ACT principles to help clients maintain sobriety and build meaningful lives in recovery through values-based action.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "18",
      name: "Dr. Fatima Al-Hassan",
      specialties: ["Cultural Identity", "Immigration Stress", "Interfaith Relationships"],
      modalities: ["ACT", "Cross-Cultural Coaching", "Identity Integration"],
      location: ["MI", "IL"],
      demographics: { gender: "Female", ethnicity: "Middle Eastern", religion: "Muslim" },
      availability: 5,
      matchScore: 78,
      languages: ["English", "Arabic"],
      bio: "First-generation immigrant coach helping clients navigate cultural identity, religious practices, and integration challenges using ACT frameworks.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "19",
      name: "Jennifer Taylor",
      specialties: ["LGBTQ+ Issues", "Coming Out", "Identity Development"],
      modalities: ["ACT", "LGBTQ+ Affirmative Coaching", "Identity Work"],
      location: ["CA", "OR"],
      demographics: { gender: "Female", ethnicity: "White", religion: "None" },
      availability: 7,
      matchScore: 77,
      languages: ["English"],
      bio: "LGBTQ+ affirming ACT coach specializing in identity development, coming out processes, and building authentic relationships while navigating societal challenges.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "20",
      name: "Mark Davis",
      specialties: ["Men's Issues", "Masculinity", "Emotional Expression"],
      modalities: ["ACT", "Men's Work", "Emotional Intelligence"],
      location: ["TX", "OK"],
      demographics: { gender: "Male", ethnicity: "White", religion: "None" },
      availability: 8,
      matchScore: 76,
      languages: ["English"],
      bio: "Men's coach using ACT principles to help men develop emotional intelligence, healthy masculinity, and authentic relationships.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "21",
      name: "Dr. Aisha Johnson",
      specialties: ["Women's Empowerment", "Leadership", "Glass Ceiling"],
      modalities: ["ACT", "Leadership Coaching", "Empowerment Work"],
      location: ["NY", "PA"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "Christian" },
      availability: 4,
      matchScore: 75,
      languages: ["English"],
      bio: "Executive coach empowering women leaders to break through barriers and lead authentically using ACT principles and values-based leadership.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },

    // Fair Matches (60-74%)
    {
      id: "22",
      name: "Steven Miller",
      specialties: ["Sports Psychology", "Performance", "Competition Anxiety"],
      modalities: ["ACT", "Sports Psychology", "Performance Enhancement"],
      location: ["FL", "GA"],
      demographics: { gender: "Male", ethnicity: "White", religion: "None" },
      availability: 6,
      matchScore: 74,
      languages: ["English"],
      bio: "Former athlete and ACT coach helping competitors overcome performance anxiety and achieve peak performance through mindfulness and values alignment.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "23",
      name: "Rosa Gonzalez",
      specialties: ["Bilingual Services", "Immigration", "Family Separation"],
      modalities: ["ACT", "Immigration Support", "Family Reunification"],
      location: ["CA", "TX"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 9,
      matchScore: 73,
      languages: ["Spanish", "English"],
      bio: "Bilingual coach specializing in immigration-related stress and family dynamics, helping clients maintain hope and psychological flexibility during difficult transitions.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "24",
      name: "Dr. Benjamin Clark",
      specialties: ["Autism Spectrum", "Neurodiversity", "Social Skills"],
      modalities: ["ACT", "Neurodiversity Coaching", "Social Skills Training"],
      location: ["WA", "CA"],
      demographics: { gender: "Male", ethnicity: "White", religion: "None" },
      availability: 3,
      matchScore: 72,
      languages: ["English"],
      bio: "Neurodiversity coach helping individuals on the autism spectrum develop social skills and navigate neurotypical environments while embracing their authentic selves.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "25",
      name: "Samantha Wright",
      specialties: ["Teen Issues", "School Anxiety", "Peer Pressure"],
      modalities: ["ACT", "Adolescent Coaching", "School Success"],
      location: ["IL", "IN"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Christian" },
      availability: 8,
      matchScore: 71,
      languages: ["English"],
      bio: "Teen specialist using ACT principles to help adolescents navigate school stress, peer relationships, and identity development during crucial developmental years.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "26",
      name: "Hassan Ibrahim",
      specialties: ["Religious Integration", "Spiritual Growth", "Life Purpose"],
      modalities: ["ACT", "Spiritual Coaching", "Purpose Finding"],
      location: ["NY", "NJ"],
      demographics: { gender: "Male", ethnicity: "Middle Eastern", religion: "Muslim" },
      availability: 5,
      matchScore: 70,
      languages: ["English", "Arabic"],
      bio: "Integrating Islamic principles with ACT coaching to help clients find spiritual balance and life purpose while maintaining psychological flexibility.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "27",
      name: "Kelly O'Brien",
      specialties: ["Seniors", "Aging", "Life Transitions"],
      modalities: ["ACT", "Geriatric Coaching", "Life Review"],
      location: ["FL", "NC"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Catholic" },
      availability: 7,
      matchScore: 69,
      languages: ["English"],
      bio: "Specialized in coaching seniors through aging transitions, retirement adjustments, and finding meaning in later life stages using ACT principles.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "28",
      name: "Derek Johnson",
      specialties: ["Substance Abuse", "Behavioral Addictions", "Impulse Control"],
      modalities: ["ACT", "Addiction Coaching", "Impulse Management"],
      location: ["CO", "WY"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "None" },
      availability: 6,
      matchScore: 68,
      languages: ["English"],
      bio: "Recovery coach using ACT to help clients overcome various addictions and develop healthy coping mechanisms for long-term sobriety.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "29",
      name: "Dr. Mei Lin",
      specialties: ["Academic Pressure", "Tiger Parent Issues", "Cultural Expectations"],
      modalities: ["ACT", "Academic Coaching", "Cultural Navigation"],
      location: ["CA", "WA"],
      demographics: { gender: "Female", ethnicity: "Chinese American", religion: "None" },
      availability: 4,
      matchScore: 67,
      languages: ["English", "Mandarin", "Cantonese"],
      bio: "Helping students navigate intense academic pressure and cultural expectations while maintaining mental health and personal values through ACT coaching.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "30",
      name: "Patricia Moore",
      specialties: ["Divorce Recovery", "Co-parenting", "Single Parenting"],
      modalities: ["ACT", "Divorce Coaching", "Parenting Support"],
      location: ["TX", "LA"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Christian" },
      availability: 8,
      matchScore: 66,
      languages: ["English"],
      bio: "Divorce recovery specialist helping clients navigate separation, co-parenting challenges, and rebuilding life after divorce using ACT principles.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "31",
      name: "Antonio Rivera",
      specialties: ["Machismo", "Latino Men", "Family Honor"],
      modalities: ["ACT", "Cultural Coaching", "Men's Work"],
      location: ["TX", "AZ"],
      demographics: { gender: "Male", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 7,
      matchScore: 65,
      languages: ["Spanish", "English"],
      bio: "Working with Latino men to navigate traditional cultural expectations while developing emotional intelligence and healthy relationships.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "32",
      name: "Dr. Sarah Goldberg",
      specialties: ["Medical Professionals", "Burnout", "Healthcare Stress"],
      modalities: ["ACT", "Professional Coaching", "Burnout Prevention"],
      location: ["NY", "CT"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Jewish" },
      availability: 3,
      matchScore: 64,
      languages: ["English"],
      bio: "Former physician using ACT to help healthcare professionals manage burnout, ethical dilemmas, and maintain compassion in high-stress medical environments.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "33",
      name: "Tanya Jackson",
      specialties: ["Single Mothers", "Financial Stress", "Time Management"],
      modalities: ["ACT", "Single Parent Support", "Life Management"],
      location: ["GA", "AL"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "Baptist" },
      availability: 9,
      matchScore: 63,
      languages: ["English"],
      bio: "Single mother and coach helping other single parents manage multiple responsibilities while maintaining well-being and staying connected to values.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "34",
      name: "Peter Novak",
      specialties: ["Eastern European", "Immigration", "Language Barriers"],
      modalities: ["ACT", "Immigration Support", "Cultural Integration"],
      location: ["IL", "WI"],
      demographics: { gender: "Male", ethnicity: "Eastern European", religion: "Orthodox" },
      availability: 6,
      matchScore: 62,
      languages: ["English", "Polish", "Russian"],
      bio: "Immigrant coach helping Eastern European clients navigate cultural transitions and language barriers while maintaining cultural identity and psychological well-being.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "35",
      name: "Dr. Maria Santos",
      specialties: ["Infertility", "Pregnancy Loss", "Reproductive Health"],
      modalities: ["ACT", "Reproductive Coaching", "Grief Support"],
      location: ["FL", "TX"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 5,
      matchScore: 61,
      languages: ["English", "Spanish"],
      bio: "Reproductive health coach helping individuals and couples navigate fertility challenges, pregnancy loss, and reproductive decisions with psychological flexibility.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Evenings"]
    },
    {
      id: "36",
      name: "Jason Park",
      specialties: ["Gaming Addiction", "Technology Balance", "Digital Wellness"],
      modalities: ["ACT", "Digital Wellness", "Behavioral Change"],
      location: ["WA", "CA"],
      demographics: { gender: "Male", ethnicity: "Korean American", religion: "None" },
      availability: 8,
      matchScore: 60,
      languages: ["English", "Korean"],
      bio: "Technology coach helping clients develop healthy relationships with digital devices and overcome gaming addiction through mindful technology use and values alignment.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },

    // Additional diverse profiles to reach 100+
    {
      id: "37",
      name: "Dr. Rebecca Smith",
      specialties: ["Chronic Illness", "Disability", "Adaptive Living"],
      modalities: ["ACT", "Disability Coaching", "Adaptive Strategies"],
      location: ["CO", "NM"],
      demographics: { gender: "Female", ethnicity: "White", religion: "None" },
      availability: 4,
      matchScore: 89,
      languages: ["English"],
      bio: "Disability coach living with chronic illness, helping clients adapt to physical limitations while maintaining quality of life and pursuing meaningful goals.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "38",
      name: "Marcus Thompson",
      specialties: ["Criminal Justice", "Reentry", "Second Chances"],
      modalities: ["ACT", "Reentry Coaching", "Life Skills"],
      location: ["PA", "OH"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "Christian" },
      availability: 7,
      matchScore: 76,
      languages: ["English"],
      bio: "Former incarcerated individual helping others successfully reintegrate into society through values-based living and psychological flexibility training.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "39",
      name: "Dr. Lakshmi Sharma",
      specialties: ["Arranged Marriage", "Cultural Traditions", "Modern Values"],
      modalities: ["ACT", "Cultural Navigation", "Relationship Coaching"],
      location: ["CA", "TX"],
      demographics: { gender: "Female", ethnicity: "Indian American", religion: "Hindu" },
      availability: 5,
      matchScore: 84,
      languages: ["English", "Hindi", "Tamil"],
      bio: "Helping clients navigate between traditional cultural expectations and modern values, particularly around marriage, career, and family decisions.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "40",
      name: "Christopher Martinez",
      specialties: ["Military Families", "Deployment", "PTSD"],
      modalities: ["ACT", "Military Family Support", "Trauma Work"],
      location: ["NC", "VA"],
      demographics: { gender: "Male", ethnicity: "Hispanic", religion: "None" },
      availability: 6,
      matchScore: 83,
      languages: ["English", "Spanish"],
      bio: "Military family specialist helping service members and families cope with deployment stress, reintegration, and trauma using ACT principles.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "41",
      name: "Dr. Emily Chang",
      specialties: ["Perfectionism", "High Achievement", "Burnout"],
      modalities: ["ACT", "Performance Coaching", "Stress Management"],
      location: ["NY", "MA"],
      demographics: { gender: "Female", ethnicity: "Korean American", religion: "None" },
      availability: 3,
      matchScore: 91,
      languages: ["English", "Korean"],
      bio: "Former high-achieving professional helping others overcome perfectionism and achieve sustainable success through psychological flexibility and values alignment.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "42",
      name: "Jamal Robinson",
      specialties: ["Police Relations", "Community Trauma", "Social Justice"],
      modalities: ["ACT", "Community Healing", "Trauma Recovery"],
      location: ["MN", "WI"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "Muslim" },
      availability: 8,
      matchScore: 79,
      languages: ["English"],
      bio: "Community activist using ACT to help individuals and communities heal from systemic trauma while working toward social justice and positive change.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "43",
      name: "Dr. Anna Petrov",
      specialties: ["International Students", "Academic Adjustment", "Cultural Shock"],
      modalities: ["ACT", "Academic Coaching", "Cultural Adaptation"],
      location: ["MA", "CT"],
      demographics: { gender: "Female", ethnicity: "Eastern European", religion: "Orthodox" },
      availability: 4,
      matchScore: 82,
      languages: ["English", "Russian", "Ukrainian"],
      bio: "Former international student helping others navigate academic systems, cultural adjustment, and homesickness while pursuing educational goals.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "44",
      name: "Roberto Silva",
      specialties: ["Farmworker Rights", "Labor Issues", "Economic Stress"],
      modalities: ["ACT", "Community Advocacy", "Economic Empowerment"],
      location: ["CA", "WA"],
      demographics: { gender: "Male", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 9,
      matchScore: 71,
      languages: ["Spanish", "English"],
      bio: "Labor organizer and coach helping farmworkers and laborers navigate economic stress, workplace rights, and family obligations through values-based action.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "45",
      name: "Dr. Jennifer Lewis",
      specialties: ["Cancer Survivors", "Medical Trauma", "Health Anxiety"],
      modalities: ["ACT", "Medical Psychology", "Survivorship Coaching"],
      location: ["TX", "OK"],
      demographics: { gender: "Female", ethnicity: "White", religion: "Christian" },
      availability: 5,
      matchScore: 85,
      languages: ["English"],
      bio: "Cancer survivor and psychologist helping others navigate medical treatment, survivorship challenges, and health-related anxiety through acceptance and commitment therapy.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "46",
      name: "Omar Hassan",
      specialties: ["Refugee Resettlement", "Trauma Recovery", "Cultural Integration"],
      modalities: ["ACT", "Refugee Support", "Trauma Healing"],
      location: ["MN", "MI"],
      demographics: { gender: "Male", ethnicity: "Somali", religion: "Muslim" },
      availability: 7,
      matchScore: 78,
      languages: ["English", "Somali", "Arabic"],
      bio: "Former refugee helping others navigate resettlement challenges, process trauma, and build new lives while maintaining cultural identity and religious practices.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "47",
      name: "Dr. Michelle Taylor",
      specialties: ["Transgender Issues", "Gender Identity", "Medical Transition"],
      modalities: ["ACT", "Gender Affirmative Coaching", "Identity Development"],
      location: ["CA", "OR"],
      demographics: { gender: "Female", ethnicity: "White", religion: "None" },
      availability: 6,
      matchScore: 88,
      languages: ["English"],
      bio: "Transgender coach helping individuals navigate gender identity exploration, medical transition decisions, and family/social acceptance through psychological flexibility.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "48",
      name: "David Kim",
      specialties: ["Start-up Stress", "Entrepreneurship", "Financial Anxiety"],
      modalities: ["ACT", "Business Coaching", "Risk Management"],
      location: ["CA", "TX"],
      demographics: { gender: "Male", ethnicity: "Korean American", religion: "None" },
      availability: 4,
      matchScore: 86,
      languages: ["English", "Korean"],
      bio: "Serial entrepreneur using ACT principles to help other business owners manage uncertainty, financial stress, and work-life balance while building successful ventures.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "49",
      name: "Dr. Carmen Rodriguez",
      specialties: ["Postpartum Depression", "Maternal Mental Health", "Work-Life Integration"],
      modalities: ["ACT", "Maternal Coaching", "Perinatal Support"],
      location: ["FL", "GA"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 8,
      matchScore: 87,
      languages: ["English", "Spanish"],
      bio: "Maternal mental health specialist helping new mothers navigate postpartum challenges, identity shifts, and work-life integration through acceptance-based strategies.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "50",
      name: "Alex Thompson",
      specialties: ["Non-binary Identity", "Workplace Discrimination", "Coming Out"],
      modalities: ["ACT", "LGBTQ+ Coaching", "Workplace Advocacy"],
      location: ["NY", "MA"],
      demographics: { gender: "Non-binary", ethnicity: "White", religion: "None" },
      availability: 7,
      matchScore: 84,
      languages: ["English"],
      bio: "Non-binary coach helping LGBTQ+ individuals navigate workplace challenges, discrimination, and identity expression while maintaining psychological well-being.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "51",
      name: "Dr. Paul Anderson",
      specialties: ["Retirement Transition", "Legacy Building", "Purpose After Career"],
      modalities: ["ACT", "Retirement Coaching", "Life Transition"],
      location: ["AZ", "NV"],
      demographics: { gender: "Male", ethnicity: "White", religion: "None" },
      availability: 5,
      matchScore: 73,
      languages: ["English"],
      bio: "Retirement specialist helping professionals transition from careers to retirement, find new purpose, and build meaningful legacies in their later years.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "52",
      name: "Fatou Diallo",
      specialties: ["African Immigrant", "Female Genital Mutilation", "Cultural Trauma"],
      modalities: ["ACT", "Cultural Healing", "Trauma Recovery"],
      location: ["NY", "NJ"],
      demographics: { gender: "Female", ethnicity: "West African", religion: "Muslim" },
      availability: 6,
      matchScore: 80,
      languages: ["English", "French", "Wolof"],
      bio: "West African immigrant helping women heal from cultural trauma, navigate Western systems, and maintain cultural connections while building new lives.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "53",
      name: "Dr. Kevin O'Connor",
      specialties: ["Irish Heritage", "Alcohol Culture", "Family Patterns"],
      modalities: ["ACT", "Cultural Coaching", "Addiction Prevention"],
      location: ["MA", "NY"],
      demographics: { gender: "Male", ethnicity: "Irish American", religion: "Catholic" },
      availability: 8,
      matchScore: 75,
      languages: ["English"],
      bio: "Irish-American coach helping clients understand cultural patterns around alcohol, family dynamics, and breaking generational cycles through awareness and choice.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "54",
      name: "Maya Patel",
      specialties: ["Arranged Marriage Pressure", "Career vs Family", "Cultural Guilt"],
      modalities: ["ACT", "Cultural Navigation", "Decision Making"],
      location: ["CA", "IL"],
      demographics: { gender: "Female", ethnicity: "Indian American", religion: "Hindu" },
      availability: 7,
      matchScore: 83,
      languages: ["English", "Hindi", "Gujarati"],
      bio: "Second-generation Indian-American helping clients balance family expectations with personal choices around marriage, career, and lifestyle decisions.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "55",
      name: "Dr. James Wilson",
      specialties: ["Intellectual Disability", "Special Needs", "Family Support"],
      modalities: ["ACT", "Special Needs Coaching", "Family Systems"],
      location: ["WA", "OR"],
      demographics: { gender: "Male", ethnicity: "White", religion: "Christian" },
      availability: 4,
      matchScore: 77,
      languages: ["English"],
      bio: "Special needs father and coach helping families navigate intellectual disabilities, advocate for services, and maintain family well-being through challenging circumstances.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "56",
      name: "Esperanza Morales",
      specialties: ["Domestic Violence", "Survivor Empowerment", "Safety Planning"],
      modalities: ["ACT", "Trauma Recovery", "Empowerment Coaching"],
      location: ["TX", "CA"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 9,
      matchScore: 81,
      languages: ["Spanish", "English"],
      bio: "Domestic violence survivor helping other women develop safety plans, rebuild confidence, and create violence-free lives through empowerment and values work.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "57",
      name: "Dr. Richard Chang",
      specialties: ["Model Minority Myth", "Asian Mental Health", "Academic Pressure"],
      modalities: ["ACT", "Cultural Psychology", "Academic Support"],
      location: ["CA", "WA"],
      demographics: { gender: "Male", ethnicity: "Taiwanese American", religion: "None" },
      availability: 3,
      matchScore: 89,
      languages: ["English", "Mandarin"],
      bio: "Challenging model minority stereotypes while helping Asian Americans address mental health stigma, academic pressure, and authentic self-expression.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "58",
      name: "Aaliyah Johnson",
      specialties: ["Black Girl Magic", "Intersectionality", "Professional Success"],
      modalities: ["ACT", "Empowerment Coaching", "Professional Development"],
      location: ["GA", "DC"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "None" },
      availability: 6,
      matchScore: 86,
      languages: ["English"],
      bio: "Empowering Black women to navigate intersectional challenges in professional settings while maintaining authenticity and achieving career goals.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "59",
      name: "Dr. Giuseppe Rossi",
      specialties: ["Italian Family Dynamics", "Generational Trauma", "Cultural Pride"],
      modalities: ["ACT", "Family Therapy", "Cultural Work"],
      location: ["NY", "NJ"],
      demographics: { gender: "Male", ethnicity: "Italian American", religion: "Catholic" },
      availability: 5,
      matchScore: 74,
      languages: ["English", "Italian"],
      bio: "Italian-American psychologist helping families understand generational patterns, heal cultural trauma, and maintain cultural pride while adapting to modern life.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "60",
      name: "Stephanie Martinez",
      specialties: ["Blended Families", "Step-parenting", "Family Integration"],
      modalities: ["ACT", "Family Coaching", "Relationship Building"],
      location: ["AZ", "NM"],
      demographics: { gender: "Female", ethnicity: "Hispanic", religion: "None" },
      availability: 8,
      matchScore: 76,
      languages: ["English", "Spanish"],
      bio: "Blended family specialist helping step-parents and children navigate complex family dynamics and build strong, loving relationships through acceptance and understanding.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "61",
      name: "Dr. Tai Nakamura",
      specialties: ["Japanese Work Culture", "Karoshi Prevention", "Work-Life Balance"],
      modalities: ["ACT", "Cultural Coaching", "Stress Management"],
      location: ["CA", "HI"],
      demographics: { gender: "Male", ethnicity: "Japanese American", religion: "Buddhist" },
      availability: 4,
      matchScore: 85,
      languages: ["English", "Japanese"],
      bio: "Japanese-American coach helping professionals navigate intense work cultures, prevent burnout, and find balance between achievement and well-being.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Evenings"]
    },
    {
      id: "62",
      name: "Ruby Williams",
      specialties: ["Hair and Beauty Standards", "Colorism", "Self-Acceptance"],
      modalities: ["ACT", "Self-Acceptance Work", "Beauty Standards"],
      location: ["LA", "TX"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "Christian" },
      availability: 7,
      matchScore: 82,
      languages: ["English"],
      bio: "Beauty industry professional helping women of color navigate colorism, hair politics, and beauty standards while developing authentic self-acceptance and confidence.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "63",
      name: "Dr. Ahmed Al-Rashid",
      specialties: ["Post-9/11 Discrimination", "Muslim Identity", "Religious Practice"],
      modalities: ["ACT", "Religious Coaching", "Discrimination Recovery"],
      location: ["MI", "IL"],
      demographics: { gender: "Male", ethnicity: "Arab American", religion: "Muslim" },
      availability: 6,
      matchScore: 79,
      languages: ["English", "Arabic"],
      bio: "Muslim coach helping individuals navigate post-9/11 discrimination, maintain religious practice in secular environments, and build bridges between communities.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "64",
      name: "Dakota WhiteEagle",
      specialties: ["Native American Identity", "Historical Trauma", "Cultural Reclamation"],
      modalities: ["ACT", "Indigenous Healing", "Cultural Recovery"],
      location: ["SD", "MT"],
      demographics: { gender: "Non-binary", ethnicity: "Native American", religion: "Traditional" },
      availability: 8,
      matchScore: 77,
      languages: ["English", "Lakota"],
      bio: "Two-Spirit coach helping Native Americans heal from historical trauma, reclaim cultural identity, and navigate between traditional and contemporary worlds.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "65",
      name: "Dr. Rachel Goldstein",
      specialties: ["Jewish Identity", "Holocaust Legacy", "Intergenerational Trauma"],
      modalities: ["ACT", "Trauma Recovery", "Cultural Identity"],
      location: ["NY", "FL"],
      demographics: { gender: "Female", ethnicity: "Jewish", religion: "Jewish" },
      availability: 5,
      matchScore: 78,
      languages: ["English", "Hebrew"],
      bio: "Third-generation Holocaust survivor helping Jewish individuals process intergenerational trauma, maintain cultural identity, and build resilience for future generations.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "66",
      name: "Miguel Santos",
      specialties: ["Undocumented Status", "DACA", "Immigration Anxiety"],
      modalities: ["ACT", "Immigration Support", "Anxiety Management"],
      location: ["CA", "TX"],
      demographics: { gender: "Male", ethnicity: "Hispanic", religion: "Catholic" },
      availability: 9,
      matchScore: 73,
      languages: ["Spanish", "English"],
      bio: "DACA recipient and immigration advocate helping undocumented individuals manage anxiety, build resilience, and pursue goals despite uncertain legal status.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "67",
      name: "Dr. Keiko Tanaka",
      specialties: ["Hikikomori", "Social Withdrawal", "Japanese Culture"],
      modalities: ["ACT", "Social Skills", "Cultural Coaching"],
      location: ["CA", "WA"],
      demographics: { gender: "Female", ethnicity: "Japanese American", religion: "None" },
      availability: 4,
      matchScore: 71,
      languages: ["English", "Japanese"],
      bio: "Specialist in social withdrawal and isolation, helping individuals gradually re-engage with society while respecting cultural factors and personal pace.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "68",
      name: "Zara Mohammed",
      specialties: ["Hijab Discrimination", "Muslim Women", "Workplace Rights"],
      modalities: ["ACT", "Discrimination Response", "Empowerment Work"],
      location: ["TX", "CA"],
      demographics: { gender: "Female", ethnicity: "Pakistani American", religion: "Muslim" },
      availability: 7,
      matchScore: 80,
      languages: ["English", "Urdu"],
      bio: "Muslim women's advocate helping hijabi women navigate workplace discrimination, assert their rights, and maintain religious practice in professional environments.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "69",
      name: "Dr. Sean O'Malley",
      specialties: ["Police Officers", "First Responder Stress", "Moral Injury"],
      modalities: ["ACT", "First Responder Support", "Moral Injury Recovery"],
      location: ["NY", "PA"],
      demographics: { gender: "Male", ethnicity: "Irish American", religion: "Catholic" },
      availability: 6,
      matchScore: 75,
      languages: ["English"],
      bio: "Former police officer helping first responders process moral injury, manage occupational stress, and maintain humanity in challenging professional environments.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "70",
      name: "Isabella Garcia",
      specialties: ["Quinceañera Pressure", "Cultural Expectations", "Teen Identity"],
      modalities: ["ACT", "Teen Coaching", "Cultural Navigation"],
      location: ["TX", "AZ"],
      demographics: { gender: "Female", ethnicity: "Mexican American", religion: "Catholic" },
      availability: 8,
      matchScore: 74,
      languages: ["Spanish", "English"],
      bio: "Teen specialist helping Latina adolescents navigate cultural traditions, family expectations, and personal identity development during crucial teenage years.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },

    // Additional profiles to reach 100+
    {
      id: "71",
      name: "Dr. Thomas Black",
      specialties: ["Executive Stress", "Leadership Burnout", "Corporate Culture"],
      modalities: ["ACT", "Executive Coaching", "Leadership Development"],
      location: ["NY", "CT"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "None" },
      availability: 3,
      matchScore: 88,
      languages: ["English"],
      bio: "C-suite executive turned coach helping other leaders navigate high-pressure environments while maintaining authenticity and personal values.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "72",
      name: "Hannah Foster",
      specialties: ["Adoption Issues", "Identity Questions", "Family Dynamics"],
      modalities: ["ACT", "Adoption Coaching", "Identity Work"],
      location: ["OR", "WA"],
      demographics: { gender: "Female", ethnicity: "Mixed Race", religion: "None" },
      availability: 6,
      matchScore: 84,
      languages: ["English"],
      bio: "Adoptee helping others navigate adoption-related identity questions, family dynamics, and the search for biological connections through acceptance-based approaches.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "73",
      name: "Dr. Victor Petrov",
      specialties: ["Soviet Legacy", "Authoritarianism Recovery", "Freedom Anxiety"],
      modalities: ["ACT", "Political Trauma", "Cultural Healing"],
      location: ["NY", "NJ"],
      demographics: { gender: "Male", ethnicity: "Russian American", religion: "Orthodox" },
      availability: 5,
      matchScore: 72,
      languages: ["English", "Russian"],
      bio: "Former Soviet Union resident helping immigrants process political trauma, navigate freedom anxiety, and adapt to democratic societies while maintaining cultural identity.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "74",
      name: "Sophia Chen",
      specialties: ["Only Child Pressure", "Academic Excellence", "Filial Piety"],
      modalities: ["ACT", "Academic Coaching", "Family Dynamics"],
      location: ["CA", "WA"],
      demographics: { gender: "Female", ethnicity: "Chinese American", religion: "None" },
      availability: 7,
      matchScore: 86,
      languages: ["English", "Mandarin"],
      bio: "Only child helping others navigate intense family pressure, academic expectations, and the balance between filial piety and personal autonomy.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "75",
      name: "Dr. Amara Okafor",
      specialties: ["Nigerian Culture", "Academic Achievement", "Professional Success"],
      modalities: ["ACT", "Cultural Coaching", "Professional Development"],
      location: ["TX", "GA"],
      demographics: { gender: "Female", ethnicity: "Nigerian American", religion: "Christian" },
      availability: 4,
      matchScore: 83,
      languages: ["English", "Igbo"],
      bio: "Nigerian-American professional helping first-generation immigrants balance cultural expectations with personal career goals and American professional culture.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "76",
      name: "Carlos Mendez",
      specialties: ["Border Town Dynamics", "Bicultural Identity", "Family Loyalty"],
      modalities: ["ACT", "Bicultural Coaching", "Identity Integration"],
      location: ["TX", "CA"],
      demographics: { gender: "Male", ethnicity: "Mexican American", religion: "Catholic" },
      availability: 8,
      matchScore: 77,
      languages: ["Spanish", "English"],
      bio: "Border town native helping clients navigate bicultural identity, family loyalty conflicts, and the unique challenges of living between two cultures.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "77",
      name: "Dr. Elizabeth Murphy",
      specialties: ["Irish Catholic Guilt", "Religious Trauma", "Spiritual Recovery"],
      modalities: ["ACT", "Religious Trauma Recovery", "Spiritual Coaching"],
      location: ["MA", "RI"],
      demographics: { gender: "Female", ethnicity: "Irish American", religion: "None" },
      availability: 6,
      matchScore: 76,
      languages: ["English"],
      bio: "Former nun helping individuals recover from religious trauma, process Catholic guilt, and develop healthy spirituality or secular meaning-making systems.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "78",
      name: "Jaime Washington",
      specialties: ["Biracial Identity", "Code-Switching", "Belonging Issues"],
      modalities: ["ACT", "Identity Coaching", "Belonging Work"],
      location: ["IL", "WI"],
      demographics: { gender: "Male", ethnicity: "Biracial", religion: "None" },
      availability: 7,
      matchScore: 81,
      languages: ["English"],
      bio: "Biracial coach helping mixed-race individuals navigate identity questions, code-switching challenges, and find belonging in multiple communities.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "79",
      name: "Dr. Fatima Benjelloun",
      specialties: ["French Colonial Legacy", "Moroccan Culture", "Immigration"],
      modalities: ["ACT", "Colonial Trauma", "Cultural Integration"],
      location: ["NY", "CA"],
      demographics: { gender: "Female", ethnicity: "Moroccan American", religion: "Muslim" },
      availability: 5,
      matchScore: 79,
      languages: ["English", "French", "Arabic"],
      bio: "Moroccan immigrant helping North African clients process colonial legacy trauma, navigate Western integration, and maintain cultural-religious identity.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "80",
      name: "Ryan Kelly",
      specialties: ["Working Class Pride", "Educational Mobility", "Class Guilt"],
      modalities: ["ACT", "Class Navigation", "Educational Support"],
      location: ["PA", "OH"],
      demographics: { gender: "Male", ethnicity: "White", religion: "Catholic" },
      availability: 8,
      matchScore: 74,
      languages: ["English"],
      bio: "First-generation college graduate helping working-class individuals navigate educational and economic mobility while maintaining connection to their roots.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "81",
      name: "Dr. Priyanka Gupta",
      specialties: ["Medical School Pressure", "Indian Parents", "Career vs Marriage"],
      modalities: ["ACT", "Academic Coaching", "Cultural Navigation"],
      location: ["CA", "TX"],
      demographics: { gender: "Female", ethnicity: "Indian American", religion: "Hindu" },
      availability: 4,
      matchScore: 87,
      languages: ["English", "Hindi"],
      bio: "Medical professional helping Indian-American students balance parental expectations for medical careers with personal interests and relationship decisions.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "82",
      name: "Marcus Johnson",
      specialties: ["Police Brutality Trauma", "Community Healing", "Activism Burnout"],
      modalities: ["ACT", "Community Trauma", "Activist Support"],
      location: ["MN", "IL"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "Christian" },
      availability: 6,
      matchScore: 78,
      languages: ["English"],
      bio: "Community organizer helping individuals and communities heal from police brutality trauma while sustaining long-term activism without burnout.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "83",
      name: "Dr. Elena Kowalski",
      specialties: ["Polish Immigration", "Economic Migration", "Family Separation"],
      modalities: ["ACT", "Immigration Support", "Family Reunification"],
      location: ["IL", "NY"],
      demographics: { gender: "Female", ethnicity: "Polish American", religion: "Catholic" },
      availability: 7,
      matchScore: 73,
      languages: ["English", "Polish"],
      bio: "Economic immigrant helping Polish families navigate separation, economic pressure, and maintaining family bonds across international distances.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "84",
      name: "Jordan Smith",
      specialties: ["Foster Care System", "Aging Out", "Relationship Building"],
      modalities: ["ACT", "Foster Care Support", "Relationship Coaching"],
      location: ["CA", "NV"],
      demographics: { gender: "Non-binary", ethnicity: "Mixed Race", religion: "None" },
      availability: 8,
      matchScore: 82,
      languages: ["English"],
      bio: "Foster care survivor helping youth and adults who aged out of the system build healthy relationships, develop life skills, and create chosen families.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "85",
      name: "Dr. Hassan Al-Mahmoud",
      specialties: ["Palestinian Identity", "Diaspora Experience", "Political Activism"],
      modalities: ["ACT", "Political Psychology", "Diaspora Support"],
      location: ["MI", "CA"],
      demographics: { gender: "Male", ethnicity: "Palestinian American", religion: "Muslim" },
      availability: 5,
      matchScore: 76,
      languages: ["English", "Arabic"],
      bio: "Palestinian-American coach helping diaspora communities maintain cultural identity, process political trauma, and engage in activism while maintaining mental health.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "86",
      name: "Maria Gutierrez",
      specialties: ["Domestic Worker Rights", "Economic Justice", "Family Support"],
      modalities: ["ACT", "Labor Rights", "Economic Empowerment"],
      location: ["TX", "CA"],
      demographics: { gender: "Female", ethnicity: "El Salvadoran", religion: "Catholic" },
      availability: 9,
      matchScore: 71,
      languages: ["Spanish", "English"],
      bio: "Former domestic worker advocating for labor rights and helping immigrant women navigate economic challenges while supporting families across borders.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "87",
      name: "Dr. Hiroshi Yamamoto",
      specialties: ["Japanese Work Ethic", "Salaryman Culture", "Mental Health Stigma"],
      modalities: ["ACT", "Cultural Coaching", "Mental Health Advocacy"],
      location: ["CA", "WA"],
      demographics: { gender: "Male", ethnicity: "Japanese American", religion: "None" },
      availability: 4,
      matchScore: 75,
      languages: ["English", "Japanese"],
      bio: "Former salaryman helping Japanese professionals challenge work culture extremes, address mental health stigma, and find sustainable life balance.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Evenings"]
    },
    {
      id: "88",
      name: "Aisha Williams",
      specialties: ["Natural Hair Movement", "Workplace Discrimination", "Self-Expression"],
      modalities: ["ACT", "Identity Coaching", "Discrimination Response"],
      location: ["GA", "NC"],
      demographics: { gender: "Female", ethnicity: "Black", religion: "None" },
      availability: 7,
      matchScore: 80,
      languages: ["English"],
      bio: "Natural hair advocate helping Black women navigate workplace hair discrimination, embrace natural beauty, and advocate for inclusive policies.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "89",
      name: "Dr. Giovanni Romano",
      specialties: ["Italian Machismo", "Emotional Expression", "Family Honor"],
      modalities: ["ACT", "Cultural Coaching", "Emotional Development"],
      location: ["NY", "NJ"],
      demographics: { gender: "Male", ethnicity: "Italian American", religion: "Catholic" },
      availability: 6,
      matchScore: 72,
      languages: ["English", "Italian"],
      bio: "Italian-American coach helping men challenge traditional machismo expectations while honoring family values and developing emotional intelligence.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "90",
      name: "Tiffany Chen",
      specialties: ["Asian Beauty Standards", "Plastic Surgery Pressure", "Self-Acceptance"],
      modalities: ["ACT", "Body Image Work", "Cultural Beauty Standards"],
      location: ["CA", "NY"],
      demographics: { gender: "Female", ethnicity: "Taiwanese American", religion: "None" },
      availability: 8,
      matchScore: 84,
      languages: ["English", "Mandarin"],
      bio: "Challenging Asian beauty standards and plastic surgery pressure while helping clients develop authentic self-acceptance and resist cultural appearance expectations.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "91",
      name: "Dr. Malik Thompson",
      specialties: ["Black Fatherhood", "Criminal Justice System", "Breaking Cycles"],
      modalities: ["ACT", "Fatherhood Coaching", "System Navigation"],
      location: ["CA", "TX"],
      demographics: { gender: "Male", ethnicity: "Black", religion: "None" },
      availability: 5,
      matchScore: 77,
      languages: ["English"],
      bio: "Father and advocate helping Black men navigate fatherhood challenges, criminal justice system interactions, and break generational cycles of trauma.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "92",
      name: "Carmen Delgado",
      specialties: ["Telenovela Culture", "Romantic Expectations", "Reality vs Fantasy"],
      modalities: ["ACT", "Relationship Coaching", "Media Literacy"],
      location: ["FL", "TX"],
      demographics: { gender: "Female", ethnicity: "Colombian American", religion: "Catholic" },
      availability: 7,
      matchScore: 74,
      languages: ["Spanish", "English"],
      bio: "Media literacy coach helping Latina women separate telenovela-influenced romantic expectations from healthy relationship realities through mindful awareness.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "93",
      name: "Dr. Wei Zhang",
      specialties: ["One Child Policy Legacy", "Sibling Envy", "Collectivist Pressure"],
      modalities: ["ACT", "Cultural Psychology", "Individual vs Collective"],
      location: ["CA", "WA"],
      demographics: { gender: "Male", ethnicity: "Chinese American", religion: "None" },
      availability: 4,
      matchScore: 83,
      languages: ["English", "Mandarin"],
      bio: "One-child policy generation member helping clients navigate individualism vs collectivism, sibling envy in American families, and cultural pressure expectations.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "94",
      name: "Lila Patel",
      specialties: ["Bollywood Influence", "Marriage Expectations", "Career Dreams"],
      modalities: ["ACT", "Cultural Coaching", "Dream Pursuit"],
      location: ["CA", "TX"],
      demographics: { gender: "Female", ethnicity: "Indian American", religion: "Hindu" },
      availability: 6,
      matchScore: 81,
      languages: ["English", "Hindi"],
      bio: "Former Bollywood aspirant helping young Indian-Americans separate media influence from personal dreams while navigating family marriage expectations.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "95",
      name: "Dr. Kwame Asante",
      specialties: ["African Heritage", "Diaspora Connection", "Cultural Reclamation"],
      modalities: ["ACT", "Cultural Recovery", "Heritage Work"],
      location: ["NY", "GA"],
      demographics: { gender: "Male", ethnicity: "Ghanaian American", religion: "Christian" },
      availability: 8,
      matchScore: 78,
      languages: ["English", "Twi"],
      bio: "Ghanaian-American coach helping African diaspora reconnect with heritage, process disconnection trauma, and build authentic cultural identity in America.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "96",
      name: "Isabella Rodriguez",
      specialties: ["Quinceañera Alternatives", "Modern Traditions", "Cultural Evolution"],
      modalities: ["ACT", "Cultural Innovation", "Tradition Adaptation"],
      location: ["TX", "CA"],
      demographics: { gender: "Female", ethnicity: "Mexican American", religion: "None" },
      availability: 7,
      matchScore: 75,
      languages: ["English", "Spanish"],
      bio: "Cultural innovator helping families adapt traditional celebrations like quinceañeras to reflect modern values while honoring cultural significance.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "97",
      name: "Dr. Raj Mehta",
      specialties: ["Tech Industry Stress", "Silicon Valley Culture", "Work Addiction"],
      modalities: ["ACT", "Tech Industry Coaching", "Work-Life Integration"],
      location: ["CA"],
      demographics: { gender: "Male", ethnicity: "Indian American", religion: "None" },
      availability: 3,
      matchScore: 86,
      languages: ["English", "Hindi"],
      bio: "Former tech executive helping Silicon Valley professionals overcome work addiction, manage industry pressure, and find meaning beyond financial success.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    },
    {
      id: "98",
      name: "Zoe Martinez",
      specialties: ["Genderfluid Identity", "Pronouns", "Family Education"],
      modalities: ["ACT", "Gender Identity Coaching", "Family Education"],
      location: ["OR", "WA"],
      demographics: { gender: "Non-binary", ethnicity: "Hispanic", religion: "None" },
      availability: 8,
      matchScore: 82,
      languages: ["English", "Spanish"],
      bio: "Genderfluid coach helping individuals explore gender identity, navigate pronouns, and educate families about gender diversity through compassionate communication.",
      sexualOrientation: "LGBTQ+",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "99",
      name: "Dr. Samuel Cohen",
      specialties: ["Holocaust Education", "Antisemitism", "Jewish Pride"],
      modalities: ["ACT", "Cultural Education", "Pride Building"],
      location: ["NY", "FL"],
      demographics: { gender: "Male", ethnicity: "Jewish", religion: "Jewish" },
      availability: 5,
      matchScore: 76,
      languages: ["English", "Hebrew"],
      bio: "Holocaust educator helping Jewish individuals develop pride in identity, respond to antisemitism, and maintain cultural traditions in secular environments.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekends"]
    },
    {
      id: "100",
      name: "Dr. Grace Liu",
      specialties: ["International Adoption", "Cultural Disconnection", "Identity Formation"],
      modalities: ["ACT", "Adoption Coaching", "Cultural Reconnection"],
      location: ["WA", "OR"],
      demographics: { gender: "Female", ethnicity: "Chinese American", religion: "None" },
      availability: 6,
      matchScore: 85,
      languages: ["English"],
      bio: "Internationally adopted coach helping other adoptees navigate cultural disconnection, explore birth culture, and form integrated identity while honoring adoptive families.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Afternoons", "Weekends"]
    },
    {
      id: "101",
      name: "Adriana Valdez",
      specialties: ["Dreamer Identity", "DACA Anxiety", "Educational Pursuit"],
      modalities: ["ACT", "Immigration Coaching", "Educational Support"],
      location: ["CA", "TX"],
      demographics: { gender: "Female", ethnicity: "Mexican American", religion: "Catholic" },
      availability: 9,
      matchScore: 79,
      languages: ["English", "Spanish"],
      bio: "DACA recipient and first-generation college graduate helping other Dreamers navigate educational opportunities, immigration anxiety, and building futures despite uncertainty.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Evenings", "Weekends"]
    },
    {
      id: "102",
      name: "Dr. Erik Johansson",
      specialties: ["Scandinavian Culture", "Social Democracy", "Work-Life Balance"],
      modalities: ["ACT", "Cultural Coaching", "Balance Work"],
      location: ["WA", "MN"],
      demographics: { gender: "Male", ethnicity: "Swedish American", religion: "None" },
      availability: 4,
      matchScore: 73,
      languages: ["English", "Swedish"],
      bio: "Scandinavian-American coach helping clients integrate Nordic values of work-life balance, social democracy, and lagom (balance) into American professional life.",
      sexualOrientation: "Straight / heterosexual",
      availableTimes: ["Weekday Mornings", "Weekday Afternoons"]
    }
  ];

  res.json(matches);
}; 